# Step 1: Build React app
FROM node:20-alpine as builder
WORKDIR /app
COPY Frontend/package*.json ./
RUN npm install
COPY Frontend/ ./
RUN npm run build

# Step 2: Serve with NGINX
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY ./nginx-frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80