"""
Configuration module for the RAG Chatbot application.
"""

from config.settings import (
    ENV_CHROMA_PATH as CHROMA_PATH,
    ENV_COLLECTION_NAME as COLLECTION_NAME,
    ENV_EMBEDDING_MODEL as EMBEDDING_MODEL,
    ENV_DEFAULT_LLM as DEFAULT_LLM,
    ENV_MAX_SEARCH_RESULTS as MAX_SEARCH_RESULTS,
    ENV_MAX_DISPLAY_RESULTS as MAX_DISPLAY_RESULTS,
    ENV_MAX_RAG_CONTEXT as MAX_RAG_CONTEXT,
    DISABLE_CUDA,
    AVAILABLE_MODELS,
    APP_TITLE,
    APP_DESCRIPTION
)

__all__ = [
    "CHROMA_PATH",
    "COLLECTION_NAME",
    "EMBEDDING_MODEL",
    "DEFAULT_LLM",
    "AVAILABLE_MODELS",
    "MAX_SEARCH_RESULTS",
    "MAX_DISPLAY_RESULTS",
    "MAX_RAG_CONTEXT",
    "DISABLE_CUDA",
    "APP_TITLE",
    "APP_DESCRIPTION"
]